In [2]:
import pandas as pd

In [4]:
df1= pd.read_excel("monetaryexcel.xlsx")

In [5]:
df1.head()

,Date,Reserve Money (M0) (a),Broad Money (M2) (b),Currency held by the Public,Demand Deposits held by the Public,Narrow Money (M1) \n(c) \n (1) + (2),Time and Savings Deposits held by the Public,Broad Money (M2b) \n(d) \n (3) + (4),Net Foreign Assets of Monetary Authorities (e),Net Foreign Assets of Commercial Banks,Net Foreign Assets (NFA) \n(5) + (6),Net Credit granted to the Government by Central Bank,Net Credit granted to the Government by Commercial Banks,Net Credit granted to the Government (NCG)\n(8) + (9),Credit granted to Public Corporations by Commercial Banks,Credit granted to the Private Sector by Commercial Banks,Domestic Credit \n(10) + (11) + (12),Other Items (net),Net Domestic Assets (NDA) \n (13) + (14),Broad Money (M2b)\n (7) + (15)
0,1995-12-01,78587,228536,42199,33019,75218,184224,259442,73662,-8917,64745,24418,14244,38662,13305,210703,262670,-67974,194696,259441
1,1996-01-01,77071,228090,41074,32709,73783,186698,260481,76259,-9030,67229,20977,19818,40795,12214,214979,267988,-74735,193253,260482
2,1996-02-01,79586,234199,42317,35123,77440,192056,269496,79977,-9413,70564,17116,23122,40238,13277,213145,266660,-67727,198933,269497
3,1996-03-01,82915,239178,45066,36730,81796,190756,272552,80825,-11637,69188,20036,23581,43617,12455,219279,275351,-71988,203363,272551
4,1996-04-01,80873,241893,43480,35998,79478,198947,278425,79963,-8751,71212,18526,24564,43090,13039,220249,276378,-69166,207212,278424

In [6]:
df1.dtypes

Date                                                         datetime64[ns]
Reserve Money (M0)  (a)                                               int64
Broad Money (M2) (b)                                                  int64
Currency held by the Public                                           int64
Demand Deposits held by the Public                                    int64
Narrow Money (M1) \n(c)    \n (1) + (2)                               int64
Time and Savings Deposits held by the Public                          int64
Broad Money (M2b) \n(d)            \n (3) + (4)                       int64
Net Foreign Assets of Monetary Authorities (e)                        int64
Net Foreign Assets of Commercial Banks                                int64
Net Foreign Assets (NFA) \n(5) + (6)                                  int64
Net Credit granted to the Government by Central Bank                  int64
Net Credit granted to the Government by Commercial Banks              int64
Net Credit granted to the Government (NCG)\n(8) + (9)                 int64
Credit granted to Public Corporations by Commercial Banks             int64
Credit granted to the Private Sector by Commercial Banks              int64
Domestic Credit \n(10) + (11) + (12)                                  int64
Other Items (net)                                                     int64
Net Domestic Assets  (NDA)       \n (13) + (14)                       int64
Broad Money (M2b)\n (7) + (15)                                        int64
dtype: object

In [7]:
df1.isnull().sum()

Date                                                         0
Reserve Money (M0)  (a)                                      0
Broad Money (M2) (b)                                         0
Currency held by the Public                                  0
Demand Deposits held by the Public                           0
Narrow Money (M1) \n(c)    \n (1) + (2)                      0
Time and Savings Deposits held by the Public                 0
Broad Money (M2b) \n(d)            \n (3) + (4)              0
Net Foreign Assets of Monetary Authorities (e)               0
Net Foreign Assets of Commercial Banks                       0
Net Foreign Assets (NFA) \n(5) + (6)                         0
Net Credit granted to the Government by Central Bank         0
Net Credit granted to the Government by Commercial Banks     0
Net Credit granted to the Government (NCG)\n(8) + (9)        0
Credit granted to Public Corporations by Commercial Banks    0
Credit granted to the Private Sector by Commercial Banks     0
Domestic Credit \n(10) + (11) + (12)                         0
Other Items (net)                                            0
Net Domestic Assets  (NDA)       \n (13) + (14)              0
Broad Money (M2b)\n (7) + (15)                               0
dtype: int64

In [8]:
df1.duplicated().sum()

0

In [9]:
df1.to_csv('Monetary_stats_1995-2025.csv', index=False)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 349 entries, 0 to 348
Data columns (total 20 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Date                                                       349 non-null    datetime64[ns]
 1   Reserve Money (M0)  (a)                                    349 non-null    int64
 2   Broad Money (M2) (b)                                       349 non-null    int64
 3   Currency held by the Public                                349 non-null    int64
 4   Demand Deposits held by the Public                         349 non-null    int64
 5   Narrow Money (M1)
(c)
 (1) + (2)                      349 non-null    int64
 6   Time and Savings Deposits held by the Public               349 non-null    int64
 7   Broad Money (M2b)
(d)
 (3) + (4)              349 non-null    int64
 8   Net Foreign Assets of Monetary Authorities (e)             349 non-null    int64
 9   Net Foreign Assets of Commercial Banks                     349 non-null    int64
 10  Net Foreign Assets (NFA)
(5) + (6)                        349 non-null    int64
 11  Net Credit granted to the Government by Central Bank       349 non-null    int64
 12  Net Credit granted to the Government by Commercial Banks   349 non-null    int64
 13  Net Credit granted to the Government (NCG)
(8) + (9)       349 non-null    int64
 14  Credit granted to Public Corporations by Commercial Banks  349 non-null    int64
 15  Credit granted to the Private Sector by Commercial Banks   349 non-null    int64
 16  Domestic Credit
(10) + (11) + (12)                        349 non-null    int64
 17  Other Items (net)                                          349 non-null    int64
 18  Net Domestic Assets  (NDA)
 (13) + (14)             349 non-null    int64
 19  Broad Money (M2b)
 (7) + (15)                              349 non-null    int64
dtypes: datetime64[ns](1), int64(19)
memory usage: 54.7 KB

In [12]:
df1['Date'] = df1['Date'].astype('date64[pyarrow]')

In [13]:
df1.head()

,Date,Reserve Money (M0) (a),Broad Money (M2) (b),Currency held by the Public,Demand Deposits held by the Public,Narrow Money (M1) \n(c) \n (1) + (2),Time and Savings Deposits held by the Public,Broad Money (M2b) \n(d) \n (3) + (4),Net Foreign Assets of Monetary Authorities (e),Net Foreign Assets of Commercial Banks,Net Foreign Assets (NFA) \n(5) + (6),Net Credit granted to the Government by Central Bank,Net Credit granted to the Government by Commercial Banks,Net Credit granted to the Government (NCG)\n(8) + (9),Credit granted to Public Corporations by Commercial Banks,Credit granted to the Private Sector by Commercial Banks,Domestic Credit \n(10) + (11) + (12),Other Items (net),Net Domestic Assets (NDA) \n (13) + (14),Broad Money (M2b)\n (7) + (15)
0,1995-12-01,78587,228536,42199,33019,75218,184224,259442,73662,-8917,64745,24418,14244,38662,13305,210703,262670,-67974,194696,259441
1,1996-01-01,77071,228090,41074,32709,73783,186698,260481,76259,-9030,67229,20977,19818,40795,12214,214979,267988,-74735,193253,260482
2,1996-02-01,79586,234199,42317,35123,77440,192056,269496,79977,-9413,70564,17116,23122,40238,13277,213145,266660,-67727,198933,269497
3,1996-03-01,82915,239178,45066,36730,81796,190756,272552,80825,-11637,69188,20036,23581,43617,12455,219279,275351,-71988,203363,272551
4,1996-04-01,80873,241893,43480,35998,79478,198947,278425,79963,-8751,71212,18526,24564,43090,13039,220249,276378,-69166,207212,278424

In [14]:
df1.dtypes

Date                                                         date64[ms][pyarrow]
Reserve Money (M0)  (a)                                                    int64
Broad Money (M2) (b)                                                       int64
Currency held by the Public                                                int64
Demand Deposits held by the Public                                         int64
Narrow Money (M1) \n(c)    \n (1) + (2)                                    int64
Time and Savings Deposits held by the Public                               int64
Broad Money (M2b) \n(d)            \n (3) + (4)                            int64
Net Foreign Assets of Monetary Authorities (e)                             int64
Net Foreign Assets of Commercial Banks                                     int64
Net Foreign Assets (NFA) \n(5) + (6)                                       int64
Net Credit granted to the Government by Central Bank                       int64
Net Credit granted to the Government by Commercial Banks                   int64
Net Credit granted to the Government (NCG)\n(8) + (9)                      int64
Credit granted to Public Corporations by Commercial Banks                  int64
Credit granted to the Private Sector by Commercial Banks                   int64
Domestic Credit \n(10) + (11) + (12)                                       int64
Other Items (net)                                                          int64
Net Domestic Assets  (NDA)       \n (13) + (14)                            int64
Broad Money (M2b)\n (7) + (15)                                             int64
dtype: object